### PR TITLE
Create featureCI.yml

### PR DESCRIPTION
**Pull request by tomklecha**

### CODE REVIEW

**Comment by tomklecha** [comment]
resolve #5

**Comment by Canato** [comment]
Nice work. How you test it?

**Comment by Canato** [comment]
BTW. why this is related to login? 

Could have been a separated branch from login direct into dev

**Comment by tomklecha** [comment]
> Nice work. How you test it?

hm. you got me, i didnt test it - i just read what you sent me and used your code as example...

**Comment by tomklecha** [comment]
> BTW. why this is related to login?
> 
> Could have been a separated branch from login direct into dev

sorry, just wrong naming convention, for now i kept as a login - which in back of my head is related with me

**Comment by tomklecha** [comment]
@Canato so do you want me to merge this one ? 
Or you want me to create new CI from master branch ?

**Comment by Canato** [comment]
> Canato so do you want me to merge this one ?
> Or you want me to create new CI from master branch ?

It is your call how you gonna do it, you can wait login be merged or create a new branch. 

But I can't accept this, because:
- This changes are not part of login to merge into login
- If you target master there are much more than need for this feature

**Comment by tomklecha** [comment]
created new PR #17

**Comment by Canato** [comment]
Did on #17

**Pull request closed without merging**
