### PR TITLE
implementation of roboelectric test for navigation component

### PR DESCRIPTION
**Pull request by tomklecha**

### CODE REVIEW

**Comment by Canato** [comment]
Why roboletric, what would be the options?

**Comment by tomklecha** [comment]
roboelectric gives us andvantage to not run the UI test, but we can keep it in unit test, so we can run them on same CI, and they are lighter. UI test can be more flakey/ less reliable

**Comment by Canato** [comment]
What you think about this?
https://stackoverflow.com/questions/56821193/does-robolectric-require-java-9

**Comment by tomklecha** [comment]
yes, I saw that it require Java 9, but with @Config annotation we are able to run it with the min SDK required for project and still we can pass the tests.

**Comment by tomklecha** [comment]
ok, double checked it now. Using Version Q we cannot run the test. And we currently put is as targetSDK. 
Damn it, I was so happy to make it work. So, delete the branch ?

**Comment by tomklecha** [comment]
https://github.com/robolectric/robolectric/issues/5258#issuecomment-556282605
that says everything, no way to run on Android Q those tests without Java 9

**Comment by Canato** [comment]
How about we use espresso?

**Comment by tomklecha** [comment]
in that case I would need your help, I dont know how differently write UI test than these two techniques (androidXTest used and working on main branch, or roboelectric on this one)
The only thing I can work on is to add to feature pipeline the test build for UI test.

**Comment by Canato** [comment]
To be done into #55

**Pull request closed without merging**
